import { Job } from "../types";

export const MOCK_JOBS = [
  {
    id: "1",
    companyName: "TechCorp",
    companyLogo: "/tech-company-logo.jpg",
    companyWebsite: "https://techcorp.com",
    title: "Senior Frontend Engineer",
    jobType: "Full-time",
    description:
      "Build cutting-edge web applications with React and TypeScript",
    qualifications: ["5+ years experience", "React expertise", "TypeScript"],
    benefits: ["Health insurance", "401k", "Remote work"],
    responsibilities: [
      "Lead frontend development",
      "Code reviews",
      "Mentoring",
    ],
    location: "San Francisco, CA",
    applicationLink: "",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "2",
    companyName: "DataFlow",
    companyLogo: "/data-analytics-logo.jpg",
    companyWebsite: "https://dataflow.com",
    title: "Full Stack Engineer",
    jobType: "Full-time",
    description: "Work on our scalable data platform serving millions of users",
    qualifications: ["3+ years experience", "Node.js", "PostgreSQL"],
    benefits: ["Equity options", "Flexible hours", "Learning budget"],
    responsibilities: ["Build APIs", "Database optimization", "Deployment"],
    location: "New York, NY",
    applicationLink: "",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "3",
    companyName: "CloudNine",
    companyLogo: "/cloud-computing-logo.png",
    companyWebsite: "https://cloudnine.com",
    title: "DevOps Engineer",
    jobType: "Contract",
    description: "Infrastructure management and cloud optimization",
    qualifications: ["Kubernetes", "AWS", "Docker"],
    benefits: ["Higher hourly rate", "Flexible schedule"],
    responsibilities: ["CI/CD pipelines", "Infrastructure", "Monitoring"],
    location: "Remote",
    applicationLink: "",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "4",
    companyName: "DesignStudio",
    companyLogo: "/design-agency-logo.png",
    companyWebsite: "https://designstudio.com",
    title: "Product Designer",
    jobType: "Full-time",
    description: "Design beautiful user experiences for our product suite",
    qualifications: ["Figma proficiency", "UI/UX experience", "Design systems"],
    benefits: ["Health insurance", "Creative freedom", "Team outings"],
    responsibilities: ["UI design", "User research", "Prototyping"],
    location: "Austin, TX",
    applicationLink: "",
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
];

export const columns = [
  { id: "Applied", title: "New Applications", color: "bg-blue-500" },
  { id: "ShortListed", title: "Short Listed", color: "bg-orange-500" },
  { id: "Hired", title: "Hired", color: "bg-green-500" },
  { id: "Rejected", title: "Rejected", color: "bg-red-500" },
];

// export const jobs: Job[] = [
//   {
//     id: "1",
//     recruiterId: "rec1",
//     companyName: "TechNova Solutions",
//     companyLogo: "https://cdn.logo.com/hotlink-ok/logo1.png",
//     companyWebsite: "https://www.technova.io",
//     title: "Frontend Developer",
//     jobType: "Full-Time",
//     description:
//       "TechNova Solutions is looking for a skilled Frontend Developer to join our growing engineering team. You will work closely with designers and backend developers to build responsive, user-friendly web applications.",
//     qualifications: [
//       "Bachelor’s degree in Computer Science or related field",
//       "2+ years of experience with React or Next.js",
//       "Strong understanding of TypeScript and modern CSS frameworks",
//       "Experience with RESTful APIs and Git version control",
//     ],
//     benefits: [
//       "Remote work flexibility",
//       "Health and dental insurance",
//       "Annual performance bonus",
//       "Paid time off and holidays",
//     ],
//     responsibilities: [
//       "Develop and maintain responsive web applications using React",
//       "Collaborate with designers to improve UI/UX",
//       "Optimize performance and ensure cross-browser compatibility",
//       "Write clean, maintainable, and testable code",
//     ],
//     location: "San Francisco, CA (Hybrid)",
//     country: "USA",
//     applicationLink: "https://www.technova.io/careers/frontend-developer",
//     postedAt: Date.now(),
//   },
//   {
//     id: "2",
//     recruiterId: "rec2",
//     companyName: "BuildSmart Engineering",
//     companyLogo: "https://cdn.logo.com/hotlink-ok/logo2.png",
//     companyWebsite: "https://www.buildsmarteng.com",
//     title: "Civil Engineer",
//     jobType: "Full-Time",
//     description:
//       "BuildSmart Engineering is seeking an experienced Civil Engineer to lead infrastructure and construction projects. You will work on designing and managing sustainable urban development projects.",
//     qualifications: [
//       "Degree in Civil Engineering or related discipline",
//       "3+ years of experience in infrastructure design and construction",
//       "Knowledge of AutoCAD, Revit, and project management tools",
//       "Excellent communication and teamwork skills",
//     ],
//     benefits: [
//       "Competitive salary package",
//       "Health and travel allowance",
//       "Professional development support",
//       "Flexible working hours",
//     ],
//     responsibilities: [
//       "Plan, design, and oversee construction projects",
//       "Ensure compliance with safety and regulatory standards",
//       "Collaborate with architects, contractors, and local authorities",
//       "Manage project timelines and budgets effectively",
//     ],
//     location: "Addis Ababa",
//     country: "Ethiopia",
//     applicationLink: "https://www.buildsmarteng.com/jobs/civil-engineer",
//     postedAt: Date.now(),
//   },
//   {
//     id: "3",
//     recruiterId: "rec3",
//     companyName: "DataCore Analytics",
//     companyLogo: "https://cdn.logo.com/hotlink-ok/logo3.png",
//     companyWebsite: "https://www.datacoreanalytics.com",
//     title: "Data Analyst",
//     jobType: "Remote",
//     description:
//       "DataCore Analytics is hiring a Data Analyst to transform raw data into actionable insights for business decisions. You will collaborate with multiple teams to improve data-driven strategies.",
//     qualifications: [
//       "Bachelor’s degree in Statistics, Mathematics, or related field",
//       "Proficiency in SQL and Python",
//       "Experience with data visualization tools (Tableau, Power BI)",
//       "Strong analytical and problem-solving skills",
//     ],
//     benefits: [
//       "Remote-first culture",
//       "Learning and development budget",
//       "Flexible work hours",
//       "Annual company retreat",
//     ],
//     responsibilities: [
//       "Collect, clean, and analyze large datasets",
//       "Develop dashboards and visualizations to track key metrics",
//       "Support teams with data insights and reporting",
//       "Ensure data accuracy and integrity across systems",
//     ],
//     location: "Remote",
//     country: "Global",
//     applicationLink: "https://www.datacoreanalytics.com/careers/data-analyst",
//     postedAt: Date.now(),
//   },
//   {
//     id: "4",
//     recruiterId: "rec4",
//     companyName: "GreenLeaf Technologies",
//     companyLogo: "https://cdn.logo.com/hotlink-ok/logo4.png",
//     companyWebsite: "https://www.greenleaftech.com",
//     title: "Software QA Engineer",
//     jobType: "Full-Time",
//     description:
//       "GreenLeaf Technologies is looking for a Quality Assurance Engineer to ensure our software meets the highest standards of quality and reliability. You will design and execute test plans for web and mobile applications.",
//     qualifications: [
//       "Bachelor’s degree in Computer Science or equivalent experience",
//       "2+ years in software testing or QA roles",
//       "Familiarity with Cypress, Jest, or Playwright",
//       "Strong attention to detail and analytical mindset",
//     ],
//     benefits: [
//       "Comprehensive insurance package",
//       "Stock options and bonuses",
//       "Wellness programs",
//       "Paid parental leave",
//     ],
//     responsibilities: [
//       "Design, execute, and maintain automated and manual test cases",
//       "Identify, document, and track software defects",
//       "Collaborate with developers to improve product quality",
//       "Ensure testing coverage across multiple platforms",
//     ],
//     location: "Berlin",
//     country: "Germany",
//     applicationLink: "https://www.greenleaftech.com/jobs/software-qa-engineer",
//     postedAt: Date.now(),
//   },
//   {
//     id: "5",
//     recruiterId: "rec5",
//     companyName: "CloudStride Systems",
//     companyLogo: "https://cdn.logo.com/hotlink-ok/logo5.png",
//     companyWebsite: "https://www.cloudstride.io",
//     title: "DevOps Engineer",
//     jobType: "Contract",
//     description:
//       "CloudStride Systems is seeking a DevOps Engineer to automate and optimize infrastructure for our clients. You’ll manage CI/CD pipelines, cloud services, and system reliability.",
//     qualifications: [
//       "3+ years of experience as a DevOps or Cloud Engineer",
//       "Proficiency in AWS, Docker, and Kubernetes",
//       "Experience with CI/CD tools (Jenkins, GitHub Actions)",
//       "Scripting skills in Bash or Python",
//     ],
//     benefits: [
//       "Flexible working schedule",
//       "Remote-first team",
//       "Competitive hourly rate",
//       "Access to online learning resources",
//     ],
//     responsibilities: [
//       "Maintain cloud infrastructure on AWS",
//       "Implement and monitor CI/CD pipelines",
//       "Collaborate with developers for deployment automation",
//       "Ensure system reliability and security compliance",
//     ],
//     location: "Remote",
//     country: "Global",
//     applicationLink: "https://www.cloudstride.io/careers/devops-engineer",
//     postedAt: Date.now(),
//   },
// ];
